coderask:
  sms:
    access-key: access-key
    access-secret: access-secret
    provider: aliyun
    signName: 猿问app
    checkCodeTemplate:
      register: SMS_205610277
      login: SMS_205620231
      resetPassword: SMS_205605230
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/app1?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=GMT%2B8

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create

  redis:
    host: localhost
    port: 6379
    password: root
    database: 0

server:
  port: 9000
