spring:
  profiles: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DEMO_MYSQL_USER}
    password: ${DEMO_MYSQL_PASSWORD}
    url: jdbc:mysql://${DEMO_MYSQL:localhost:3306}/app1?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=GMT%2B8

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create

  redis:
    host: ${DEMO_REDIS_HOST:localhost}
    port: ${DEMO_REDIS_PORT:6379}
    password: ${DEMO_REDIS_PASSWORD}
    database: 0


server:
  port: 9000
  address: 127.0.0.1
